version: '3.8'
services:
  gateway:
    build: gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PORT=8080
      - SERVER_URL=http://server:9090

  server:
    build: server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PORT=9090
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=shareit
      - DB_USERNAME=admin
      - DB_PASSWORD=password

  db:
    image: postgres:15.1-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data/
      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql